name: your_app_name
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  swipe_cards: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/forest.jpg
    - assets/images/city.jpg
    - assets/images/beach.jpg
    - assets/images/mountains.jpg
    - assets/images/red.png
    - assets/images/blue.png
    - assets/images/green.png
    - assets/images/yellow.png
    - assets/images/emoticon1.png
    - assets/images/emoticon2.png
    - assets/images/emoticon3.png
    - assets/images/emoticon4.png
    - assets/images/emoticon5.png
    - assets/images/reading.jpg
    - assets/images/cooking.jpg
    - assets/images/concert.jpg
    - assets/images/hiking.png
    - assets/images/sunny.png
    - assets/images/rainy.png
    - assets/images/stormy.png
    - assets/images/cloudy.png
    - assets/images/default_background.png
    - assets/images/party.jpg
    - assets/images/volunteer.jpeg
    - assets/images/skydiving.jpg
    - assets/images/concert.jpg
    - assets/images/compass.jpg
    - assets/images/office.jpg
    - assets/images/stargazing.jpg
    - assets/images/artist.jpg
    - assets/images/teamwork.jpg
    - assets/images/puzzle.jpg
    - assets/images/leader.jpg